/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
  streamdeck?: {
    enable?: boolean;
    port?: number;
    key?: string;
    debug?: boolean;
    [k: string]: any;
  };
  rabbitmq?: {
    remote?: {
      protocol?: string;
      hostname?: string;
      username?: string;
      password?: string;
      vhost?: string;
      [k: string]: any;
    };
    local?: {
      protocol?: string;
      hostname?: string;
      username?: string;
      password?: string;
      vhost?: string;
      [k: string]: any;
    };
    [k: string]: any;
  };
  obs?: {
    enable?: boolean;
    address?: string;
    password?: string;
    names?: {
      scenes?: {
        ads?: string;
        [k: string]: any;
      };
      [k: string]: any;
    };
    [k: string]: any;
  };
  tracker?: {
    username?: string;
    password?: string;
    [k: string]: any;
  };
  fcb?: {
    postKey?: string;
    [k: string]: any;
  };
  [k: string]: any;
}
