/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Type = "image" | "prize" | "prize_generic";
export type MediaActive = {
  type: Type;
  id: string;
  mediaUUID: string;
  index: number;
  timestamp: number;
  timeElapsed: number;
} | null;

export interface MediaBox {
  rotation: {
    type: Type;
    id: string;
    mediaUUID: string;
    seconds: number;
  }[];
  current: MediaActive;
}
