/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BigbuttonPlayerMap {
	[k: string]: {
		flagcarrier: {
			/**
			 * ID of the terminal that scanned the tag (BRB1, ...)
			 */
			id: string;
			/**
			 * Group of the terminal that scanned the tag
			 */
			group: string;
			/**
			 * Timestamp of when the tag was scanned
			 */
			time: {
				/**
				 * Timestamp representation in the ISO 8601 format
				 */
				iso: string;
				/**
				 * Timestamp representation in seconds since the Unix epoch, including a fractional millisecond part
				 */
				unix: number;
			};
			/**
			 * NFC tag UID as hex string
			 */
			uid: string;
			/**
			 * Indicates if tag had a valid signature
			 */
			validSignature?: boolean;
			/**
			 * Base64 encoded ed25519 public key used to verify the tag
			 */
			pubKey?: string;
		};
		user: {
			/**
			 * UserTool ID of the user who scanned the tag (if known)
			 */
			id?: string;
			/**
			 * UserTool display name of the user who scanned the tag
			 */
			displayName: string;
		};
		/**
		 * Raw dump of scanned tags Key->Value data
		 */
		raw: {
			[k: string]: string;
		};
	}[];
}
