/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MediaBox = MediaBox1;
export type Rotation = {
	type: 'image' | 'prize' | 'prize_generic';
	id: string;
	mediaUUID: string;
	seconds: number;
	showOnIntermission: boolean;
}[];

export interface MediaBox1 {
	rotation: Rotation;
	rotationApplicable: Rotation;
	alertQueue: {
		type: 'donation' | 'subscription' | 'cheer' | 'merch' | 'therungg';
		id: string;
		data:
			| {
					name: string;
					amount: number;
					comment?: string;
			  }
			| {
					systemMsg: string;
					message?: string;
			  }
			| {
					name: string;
					amount: number;
					message: string;
			  }
			| {
					user: string;
					productName: string;
					imgURL: string;
			  }
			| {
					msg: string;
			  };
	}[];
	paused: {
		type: 'image' | 'prize' | 'prize_generic' | 'donation' | 'subscription' | 'cheer' | 'merch' | 'therungg';
		id: string;
		mediaUUID: string;
		index: number;
		timestamp: number;
		timeElapsed: number;
	} | null;
	current: {
		type: 'image' | 'prize' | 'prize_generic' | 'donation' | 'subscription' | 'cheer' | 'merch' | 'therungg';
		id: string;
		mediaUUID: string;
		index: number;
		timestamp: number;
		timeElapsed: number;
	} | null;
	lastIndex: number;
}
