/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MusicData = MusicData1;

export interface MusicData1 {
	connected: boolean;
	playing: boolean;
	track?: {
		title?: string;
		artist?: string;
		position: number;
		duration: number;
	};
}
