/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NotableDonations = {
	event: string;
	_id: number;
	donor_visiblename: string;
	amount: number;
	comment_state?: string | number;
	comment: string | null;
	time_received?: string;
	[k: string]: unknown;
}[];
